spring:
  datasource:
    url: jdbc:h2:mem:rpsdb
    driverClassName: org.h2.Driver
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true